Repository SPURB/participe, pull requests merged in 2019-05, with the labels that each got.

#60 Corrige bug no preloader
  src/components/Preloader.vue
Labels: bug

#62 Newfeature/errata
  src/_variables.scss
  src/components/Apoio.vue
  src/components/Errata.vue
  src/components/Imagem.vue
  src/components/graf/setor-central-2/infografico.vue
  src/mixins/consultasCommons.js
  src/modules/erratas.js
  src/store.js
  src/views/SetorCentral2.vue
Labels: enhancement, errata

#64 Ajusta erro id 15
  src/views/SetorCentral2.vue
Labels: errata
