Repository SPURB/participe, pull requests merged in 2019-10, with the labels that each got.

#123 Inclui badge de status de build e atualiza readme
  README.md
  package.json
  tests/e2e/integration/0_api.js
  tests/e2e/integration/1_home.js
Labels: doc

#124 Lazy loading em imagens e galerias
  src/components/Galeria.vue
  src/components/Imagem.vue
  src/mixins/fallbacks.js
  src/views/Home.vue
Labels: enhancement

#127 PIU Arco Tietê - 1ª Consulta Pública - Ultimas correcoes
  src/views/ArcoTiete.vue
Labels: rota

#125 Otimiza views e inclui testes de integração
  src/mixins/consultasCommons.js
  src/views/ParqueBrigadeiroFariaLima.vue
  src/views/ParqueDosEucaliptos.vue
  src/views/ParqueJacintoAlberto.vue
  src/views/ParqueJardimFelicidade.vue
  src/views/ParqueLajeado.vue
  src/views/PlanoCicloviario.vue
  src/views/PlanoDiretorParqueIbirapuera.vue
  src/views/PoliticaMunicipalTurismo.vue
  src/views/PremiaSampaEdicao2020.vue
  src/views/Tr156.vue
  src/views/VidaSegura.vue
  tests/e2e/integration/consultas/parque-brigadeiro-faria-lima.spec.js
  tests/e2e/integration/consultas/parque-dos-eucaliptos.spec.js
  tests/e2e/integration/consultas/parque-jacinto-alberto.spec.js
  tests/e2e/integration/consultas/parque-jardim-felicidade.spec.js
  tests/e2e/integration/consultas/parque-lajeado.spec.js
  tests/e2e/integration/consultas/pdp-ibirapuera.spec.js
  tests/e2e/integration/consultas/plano-cicloviario.spec.js
  tests/e2e/integration/consultas/politica-municipal-turismo.spec.js
  tests/e2e/integration/consultas/premia-sampa-edicao-2020.spec.js
  tests/e2e/integration/consultas/tr-156.spec.js
  tests/e2e/integration/consultas/vida-segura.spec.js
Labels: enhancement, tests

#126 PIU Jockey Club - 1ª consulta pública
  package.json
  src/App.vue
  src/components/CommentsLoader.vue
  src/components/Galeria.vue
  src/components/Imagem.vue
  src/components/Pergunta.vue
  src/mixins/commentsCommons.js
  src/mixins/fallbacks.js
  src/router.js
  src/views/JockeyClub.vue
  tests/e2e/integration/consultas/arco-tiete.spec.js
  tests/e2e/integration/consultas/jockey-club.spec.js
  vue.config.js
Labels: rota

#129 Bugfix/corrige post e corrige data de consulta
  src/components/Comments.vue
  src/views/JockeyClub.vue
Labels: bug, rota

#134 Minuta PIU Setor Central
  src/router.js
  src/views/MinutaSetorCentral.vue
  tests/e2e/integration/consultas/minuta-piu-setor-central.spec.js
  tests/e2e/support/commands.js
  vue.config.js
Labels: rota

#135 Corrige problema em Comments.vue
  src/components/Comments.vue
  src/views/JockeyClub.vue
Labels: bug

#136 Corrige mapa 8 da consulta /minuta-piu-setor-central e aplica eslint
  package-lock.json
  package.json
  src/components/LayerExplorer.vue
  src/components/Pergunta.vue
  src/views/MinutaSetorCentral.vue
  src/views/Tr156.vue
Labels: enhancement, errata
