Repository SPURB/participe, pull requests merged in 2020-01, with the labels that each got.

#160 Adicionado Jest e primeiro teste funcionando como POC
  .eslintrc.js
  jest.config.js
  package.json
  src/components/Comments.vue
  tests/unit/Comments.spec.js
Labels: tests

#173 chore(wip): arco-tiete-2 e altera tudo para apiv3
  .env
  package.json
  src/components/BtnFixedUrl.vue
  src/components/Comments.vue
  src/components/CommentsContext.vue
  src/components/CommentsLoader.vue
  src/components/CommentsOption.vue
  src/components/Galeria.vue
  src/components/LayerExplorer.vue
  src/components/Pergunta.vue
  src/components/graf/arco-tiete-2/DadosGerais.vue
  src/components/graf/arco-tiete-2/DesafiosObjetivos.vue
  src/components/graf/arco-tiete-2/Escalas.vue
  src/components/graf/arco-tiete-2/Lancamentos2.vue
  src/components/graf/arco-tiete-2/Lancamentos3.vue
  src/components/graf/arco-tiete-2/Lancamentos4.vue
  src/components/graf/arco-tiete-2/PerimetroInfoLapa.vue
  src/components/graf/arco-tiete-2/PerimetroInfoLimao.vue
  src/components/graf/arco-tiete-2/PerimetroInfoSantana.vue
  src/components/graf/arco-tiete-2/PizzaCustos.vue
  src/components/graf/arco-tiete-2/Processo2.vue
  src/components/graf/arco-tiete-2/ProgramaIntervencoes.vue
  src/mixins/consultasCommons.js
  src/router.js
  src/store.js
  src/utils/api.js
  src/views/ArcoPinheiros2.vue
  src/views/ArcoTiete2.vue
  src/views/SetorCentral2.vue
  vue.config.js
Labels: core, enhancement, rota

#180 fix: errata para arco-tiete-2
  src/views/ArcoTiete2.vue
Labels: errata

#182 rewrite: corrige parsing em mutations, otimiza metodos em store e mixins
  src/mixins/consultasCommons.js
  src/store.js
  src/views/__TEMPLATE_NOVAS_CONSULTAS__.vue
Labels: core, enhancement
